
// Generated by Skini: Thu Jul 17 2025 11:02:16 GMT+0200 (heure d’été d’Europe centrale)
"use strict"

var midiConfig = require("../serveur/midiConfig.json");

var countBusOUT = 0;
for (var i = 0; i < midiConfig.length; i++) {
  if (midiConfig[i].type === "OUT") {
    if (midiConfig[i].spec === "clipToDAW") {
      exports.busMidiDAW = countBusOUT;
    }
    countBusOUT++;
  }
}

// Piece Bitwig en OSC si la paramètre est false
// Sinon Skini parle MIDI
exports.directMidiON = true;

// Pour charger les fonctions et modules de scenes de type GOLEM
exports.scenesON = false;

exports.english = true;

/***********************************
  Paramètres du simulateur
  Si ces valeurs ne sont pas données c'est celle qui
  sont dans le simulateur qui sont utilisées
************************************/
exports.tempoMax = 501; // En ms
exports.tempoMin = 500; // En ms
exports.limiteDureeAttente = 33; // En pulsations

/********************************************************
AUTOMATE
*********************************************************/
// Pour un automate conforme à un rechargement selon les déclarations de module HipHop
exports.reactOnPlay = false;

// Pour une réaction à chaque pulsation
exports.pulsationON = false;

/*************************************
CHEMIN DES FICHIERS SONS MP3 pour les clients
Nom du sous répartoire ./sounds/xxxx
*************************************/
exports.soundFilesPath1 = "";

/***************************************
CHEMIN DES PARTITIONS DES PATTERNS ET CONFIG AVEC MUSICIENS
****************************************/
exports.avecMusicien = false; // Pour mettre en place les spécificités au jeu avec des musiciens.
exports.decalageFIFOavecMusicien = 4; // Décalage de la FIFO vide avant le premier pattern dans une FIFO.
exports.patternScorePath1 ="";

/****************************************
ACTIVATION D'ALGORITHME D'ORGANISATION DES FIFOs
Si 0 ou undefined pas d'algorithme.
Si 1 algorithme de réorganisation Début, Milieu, Fin, Neutre (DFMN)
Dans le csv, D -> 1, M -> 2, F->3, N->4 (c'est fixé dans controleAbleton.js)
Si autre ... à créer...
ATTENTION: NE JAMAIS UTILISER EN SITUATION D'INTERACTION SI L'ALGORITHME
PEUT SUPPRIMER DES PATTERNS DES FIFOs
*****************************************/
exports.algoGestionFifo = 2;
exports.shufflePatterns = false;
/*****************************************************************************

Gestion de la Matrice des possibles
Automate de gestion de la matrice des possibles

******************************************************************************/
exports.nbeDeGroupesClients = 2;

function setnbeDeGroupesClients(num) {
  this.nbeDeGroupesClients = num;
}
exports.setnbeDeGroupesClients = setnbeDeGroupesClients;

exports.simulatorInAseperateGroup = false; // Si true, le dernier groupe client est réservé au simulateur.

// Pour un contrôle des Raspberries
exports.useRaspberries = false;
exports.playBufferMessage = "test";
exports.raspOSCPort = 4000;

// La synchro Midi, Link. Synchro Bitwig OSC par défaut si Midi et Link false.
exports.synchoOnMidiClock = false;
exports.synchroLink = true;
exports.synchroSkini = false;
exports.timer = 500;
exports.gameOSCSignals = false;

exports.sensorOSC = false;
exports.tempoSensorsInit = [0,0,0,0,0,0,0,0,0,0,0,0];
exports.sensorsSensibilities = [5,5,5,5,5,5,5,5,5,5,5,5];

const groupesDesSons = [
  [ "FluteD1",1, "tank",100,51,1,"#5F6262",[],1 ],
  [ "FluteD2",2, "tank",,,1,"#5F6262",[], ],
  [ "FluteD3",3, "tank",,,1,"#5F6262",[], ],
  [ "FluteD4",4, "tank",,,1,"#5F6262",[], ],
  [ "FluteD5",5, "tank",,,1,"#5F6262",[], ],
  [ "FluteD6",6, "tank",,,1,"#5F6262",[], ],
  [ "FluteD7",7, "tank",,,1,"#5F6262",[], ],
  [ "FluteD8",8, "tank",,,1,"#5F6262",[], ],
  [ "FluteD9",9, "tank",,,1,"#5F6262",[], ],
  [ "FluteD10",10, "tank",,,1,"#5F6262",[], ],
  [ "FluteD11",11, "tank",,,1,"#5F6262",[], ],
  [ "FluteD12",12, "tank",,,1,"#5F6262",[], ],
  [ "FluteE1",13, "tank",300,51,2,"#5F6262",[],1 ],
  [ "FluteE2",14, "tank",,,2,"#5F6262",[], ],
  [ "FluteE3",15, "tank",,,2,"#5F6262",[], ],
  [ "FluteE4",16, "tank",,,2,"#5F6262",[], ],
  [ "FluteE5",17, "tank",,,2,"#5F6262",[], ],
  [ "FluteE6",18, "tank",,,2,"#5F6262",[], ],
  [ "FluteE7",19, "tank",,,2,"#5F6262",[], ],
  [ "FluteE8",20, "tank",,,2,"#5F6262",[], ],
  [ "FluteE9",21, "tank",,,2,"#5F6262",[], ],
  [ "FluteE10",22, "tank",,,2,"#5F6262",[], ],
  [ "FluteE11",23, "tank",,,2,"#5F6262",[], ],
  [ "FluteE12",24, "tank",,,2,"#5F6262",[], ],
  [ "PianoD",25, "group",100,400,20,"#039879",[],1 ],
  [ "PianoE",26, "group",300,400,20,"#039879",[],1 ],
  [ "Percu",27, "group",400,10,20,"#039879",[],1 ],
  ];
exports.groupesDesSons = groupesDesSons;
