
// Generated by Skini: Wed Nov 12 2025 18:10:23 GMT+0100 (heure normale d’Europe centrale)
"use strict"

// A utiliser si Processing en passerelle
exports.busMidiDAW = 1;

// Piece Bitwig en OSC si la paramètre est false
// Sinon Skini parle MIDI
exports.directMidiON = true;

// Pour charger les fonctions et modules de scenes de type GOLEM
exports.scenesON = false;

exports.english = true;

/***********************************
  Paramètres du simulateur
  Si ces valeurs ne sont pas données c'est celle qui
  sont dans le simulateur qui sont utilisées
************************************/
exports.tempoMax = 501; // En ms
exports.tempoMin = 399; // En ms
exports.limiteDureeAttente = 33; // En pulsations

/********************************************************
AUTOMATE
*********************************************************/
// Pour un automate conforme à un rechargement selon les déclarations de module HipHop
exports.reactOnPlay = false;

// Pour une réaction à chaque pulsation
exports.pulsationON = false;

/*************************************
CHEMIN DES FICHIERS SONS MP3 pour les clients
Nom du sous répartoire ./sounds/xxxx
*************************************/
exports.soundFilesPath1 = "";

/***************************************
CHEMIN DES PARTITIONS DES PATTERNS ET CONFIG AVEC MUSICIENS
****************************************/
exports.avecMusicien = false; // Pour mettre en place les spécificités au jeu avec des musiciens.
exports.decalageFIFOavecMusicien = 4; // Décalage de la FIFO vide avant le premier pattern dans une FIFO.
exports.patternScorePath1 ="";

/****************************************
ACTIVATION D'ALGORITHME D'ORGANISATION DES FIFOs
Si 0 ou undefined pas d'algorithme.
Si 1 algorithme de réorganisation Début, Milieu, Fin, Neutre (DFMN)
Dans le csv, D -> 1, M -> 2, F->3, N->4 (c'est fixé dans controleAbleton.js)
Si autre ... à créer...
ATTENTION: NE JAMAIS UTILISER EN SITUATION D'INTERACTION SI L'ALGORITHME
PEUT SUPPRIMER DES PATTERNS DES FIFOs
*****************************************/
exports.algoGestionFifo = 2;
exports.shufflePatterns = false;
/*****************************************************************************

Gestion de la Matrice des possibles
Automate de gestion de la matrice des possibles

******************************************************************************/
exports.nbeDeGroupesClients = 3;

function setnbeDeGroupesClients(num) {
  this.nbeDeGroupesClients = num;
}
exports.setnbeDeGroupesClients = setnbeDeGroupesClients;

exports.simulatorInAseperateGroup = false; // Si true, le dernier groupe client est réservé au simulateur.

// Pour un contrôle des Raspberries
exports.useRaspberries = false;
exports.playBufferMessage = "test";
exports.raspOSCPort = 4000;

// La synchro Midi, Link. Synchro Bitwig OSC par défaut si Midi et Link false.
exports.synchoOnMidiClock = false;
exports.synchroLink = true;
exports.synchroSkini = false;
exports.timer = 500;
exports.gameOSCSignals = false;

exports.sensorOSC = false;
exports.tempoSensorsInit = [0,0,0,0,0,0,0,0,0,0,0,0];
exports.sensorsSensibilities = [5,5,5,5,5,5,5,5,5,5,5,5];

const groupesDesSons = [
  [ "PianoC",0, "group",100,100,5,"#5F6262",[],1 ],
  [ "PianoEb",1, "group",200,100,5,"#5F6262",[],1 ],
  [ "PianoFmin",2, "group",300,100,5,"#5F6262",[],1 ],
  [ "FluteC1",3, "tank",400,100,1,"#5F6262",[],1 ],
  [ "FluteC2",5, "tank",,,1,"",[],1 ],
  [ "FluteC3",6, "tank",,,1,"",[],1 ],
  [ "FluteC4",7, "tank",,,1,"",[],1 ],
  [ "FluteC5",8, "tank",,,1,"",[],1 ],
  [ "FluteC6",9, "tank",,,1,"",[],1 ],
  [ "FluteC7",10, "tank",,,1,"",[],1 ],
  [ "FluteC8",11, "tank",,,1,"",[],1 ],
  [ "FluteC9",12, "tank",,,1,"",[],1 ],
  [ "FluteC10",13, "tank",,,1,"",[],1 ],
  [ "FluteC11",14, "tank",,,1,"",[],1 ],
  [ "FluteC12",15, "tank",,,1,"",[],1 ],
  [ "FluteC13",16, "tank",,,1,"",[],1 ],
  [ "FluteC14",17, "tank",,,1,"",[],1 ],
  [ "FluteC15",18, "tank",,,1,"",[],1 ],
  [ "FluteEb1",19, "tank",100,200,2,"#5F6262",[],1 ],
  [ "FluteEb2",20, "tank",,,2,"",[],1 ],
  [ "FluteEb3",21, "tank",,,2,"",[],1 ],
  [ "FluteEb4",22, "tank",,,2,"",[],1 ],
  [ "FluteEb5",23, "tank",,,2,"",[],1 ],
  [ "FluteEb6",24, "tank",,,2,"",[],1 ],
  [ "FluteEb7",25, "tank",,,2,"",[],1 ],
  [ "FluteEb8",26, "tank",,,2,"",[],1 ],
  [ "FluteEb9",27, "tank",,,2,"",[],1 ],
  [ "FluteEb10",28, "tank",,,2,"",[],1 ],
  [ "FluteEb11",29, "tank",,,2,"",[],1 ],
  [ "FluteEb12",30, "tank",,,2,"",[],1 ],
  [ "FluteEb13",31, "tank",,,2,"",[],1 ],
  [ "FluteEb14",32, "tank",,,2,"",[],1 ],
  [ "FluteEb15",33, "tank",,,2,"",[],1 ],
  [ "FluteFmin1",34, "tank",200,200,3,"#5F6262",[],1 ],
  [ "FluteFmin2",35, "tank",,,3,"",[],1 ],
  [ "FluteFmin3",36, "tank",,,3,"",[],1 ],
  [ "FluteFmin4",37, "tank",,,3,"",[],1 ],
  [ "FluteFmin5",38, "tank",,,3,"",[],1 ],
  [ "FluteFmin6",39, "tank",,,3,"",[],1 ],
  [ "FluteFmin7",40, "tank",,,3,"",[],1 ],
  [ "FluteFmin8",41, "tank",,,3,"",[],1 ],
  [ "FluteFmin9",42, "tank",,,3,"",[],1 ],
  [ "FluteFmin10",43, "tank",,,3,"",[],1 ],
  [ "FluteFmin11",44, "tank",,,3,"",[],1 ],
  [ "FluteFmin12",45, "tank",,,3,"",[],1 ],
  [ "FluteFmin13",46, "tank",,,3,"",[],1 ],
  [ "FluteFmin14",47, "tank",,,3,"",[],1 ],
  [ "FluteFmin15",48, "tank",,,3,"",[],1 ],
  ];
exports.groupesDesSons = groupesDesSons;
