
// Generated by Skini: Fri Jul 18 2025 15:55:02 GMT+0200 (heure d’été d’Europe centrale)
"use strict"

var midiConfig = require("../serveur/midiConfig.json");

var countBusOUT = 0;
for (var i = 0; i < midiConfig.length; i++) {
  if (midiConfig[i].type === "OUT") {
    if (midiConfig[i].spec === "clipToDAW") {
      exports.busMidiDAW = countBusOUT;
    }
    countBusOUT++;
  }
}

// Piece Bitwig en OSC si la paramètre est false
// Sinon Skini parle MIDI
exports.directMidiON = true;

// Pour charger les fonctions et modules de scenes de type GOLEM
exports.scenesON = false;

exports.english = true;

/***********************************
  Paramètres du simulateur
  Si ces valeurs ne sont pas données c'est celle qui
  sont dans le simulateur qui sont utilisées
************************************/
exports.tempoMax = 501; // En ms
exports.tempoMin = 500; // En ms
exports.limiteDureeAttente = 33; // En pulsations

/********************************************************
AUTOMATE
*********************************************************/
// Pour un automate conforme à un rechargement selon les déclarations de module HipHop
exports.reactOnPlay = false;

// Pour une réaction à chaque pulsation
exports.pulsationON = false;

/*************************************
CHEMIN DES FICHIERS SONS MP3 pour les clients
Nom du sous répartoire ./sounds/xxxx
*************************************/
exports.soundFilesPath1 = "";

/***************************************
CHEMIN DES PARTITIONS DES PATTERNS ET CONFIG AVEC MUSICIENS
****************************************/
exports.avecMusicien = false; // Pour mettre en place les spécificités au jeu avec des musiciens.
exports.decalageFIFOavecMusicien = 4; // Décalage de la FIFO vide avant le premier pattern dans une FIFO.
exports.patternScorePath1 ="";

/****************************************
ACTIVATION D'ALGORITHME D'ORGANISATION DES FIFOs
Si 0 ou undefined pas d'algorithme.
Si 1 algorithme de réorganisation Début, Milieu, Fin, Neutre (DFMN)
Dans le csv, D -> 1, M -> 2, F->3, N->4 (c'est fixé dans controleAbleton.js)
Si autre ... à créer...
ATTENTION: NE JAMAIS UTILISER EN SITUATION D'INTERACTION SI L'ALGORITHME
PEUT SUPPRIMER DES PATTERNS DES FIFOs
*****************************************/
exports.algoGestionFifo = 2;
exports.shufflePatterns = false;
/*****************************************************************************

Gestion de la Matrice des possibles
Automate de gestion de la matrice des possibles

******************************************************************************/
exports.nbeDeGroupesClients = 3;

function setnbeDeGroupesClients(num) {
  this.nbeDeGroupesClients = num;
}
exports.setnbeDeGroupesClients = setnbeDeGroupesClients;

exports.simulatorInAseperateGroup = false; // Si true, le dernier groupe client est réservé au simulateur.

// Pour un contrôle des Raspberries
exports.useRaspberries = false;
exports.playBufferMessage = "test";
exports.raspOSCPort = 4000;

// La synchro Midi, Link. Synchro Bitwig OSC par défaut si Midi et Link false.
exports.synchoOnMidiClock = false;
exports.synchroLink = true;
exports.synchroSkini = false;
exports.timer = 500;
exports.gameOSCSignals = false;

exports.sensorOSC = false;
exports.tempoSensorsInit = [0,0,0,0,0,0,0,0,0,0,0,0];
exports.sensorsSensibilities = [5,5,5,5,5,5,5,5,5,5,5,5];

const groupesDesSons = [
  [ "Viol1C",0, "group",100,200,20,"#5F6262",[],1 ],
  [ "Viol2C",1, "group",270,200,20,"#5F6262",[],1 ],
  [ "AltoC",2, "group",440,200,20,"#5F6262",[],1 ],
  [ "CelloC",3, "group",610,200,20,"#5F6262",[],1 ],
  [ "Viol1Eb",4, "group",100,300,20,"#CF1919",[],1 ],
  [ "Viol2Eb",5, "group",270,300,20,"#CF1919",[],1 ],
  [ "AltoEb",6, "group",440,300,20,"#CF1919",[],1 ],
  [ "CelloEb",7, "group",610,300,20,"#CF1919",[],1 ],
  [ "Viol1Gb",8, "group",100,400,20,"#4CAF60",[],1 ],
  [ "Viol2Gb",9, "group",270,400,20,"#4CAF60",[],1 ],
  [ "AltoGb",10, "group",440,400,20,"#4CAF60",[],1 ],
  [ "CelloGb",11, "group",610,400,20,"#4CAF60",[],1 ],
  [ "Viol1A",12, "group",100,500,20,"#008CBA",[],1 ],
  [ "Viol2A",13, "group",270,500,20,"#008CBA",[],1 ],
  [ "AltoA",14, "group",440,500,20,"#008CBA",[],1 ],
  [ "CelloA",15, "group",610,500,20,"#008CBA",[],1 ],
  [ "PianoC1",16, "tank",100,600,1,"#5F6262",[],1 ],
  [ "PianoC2",17, "tank",,,1,"",[],1 ],
  [ "PianoC3",18, "tank",,,1,"",[],1 ],
  [ "PianoC4",19, "tank",,,1,"",[],1 ],
  [ "PianoC5",20, "tank",,,1,"",[],1 ],
  [ "PianoEb1",21, "tank",270,600,2,"#CF1919",[],1 ],
  [ "PianoEb2",22, "tank",,,2,"",[],1 ],
  [ "PianoEb3",23, "tank",,,2,"",[],1 ],
  [ "PianoEb4",24, "tank",,,2,"",[],1 ],
  [ "PianoEb5",25, "tank",,,2,"",[],1 ],
  [ "PianoGb1",26, "tank",440,600,3,"#4CAF60",[],1 ],
  [ "PianoGb2",27, "tank",,,3,"",[],1 ],
  [ "PianoGb3",28, "tank",,,3,"",[],1 ],
  [ "PianoGb4",29, "tank",,,3,"",[],1 ],
  [ "PianoGb5",30, "tank",,,3,"",[],1 ],
  [ "PianoA1",31, "tank",610,600,4,"#008CBA",[],1 ],
  [ "PianoA2",32, "tank",,,4,"",[],1 ],
  [ "PianoA3",33, "tank",,,4,"",[],1 ],
  [ "PianoA4",34, "tank",,,4,"",[],1 ],
  [ "PianoA5",35, "tank",,,4,"",[],1 ],
  ];
exports.groupesDesSons = groupesDesSons;
