
// Generated by Skini: Wed Apr 03 2024 16:20:45 GMT+0200 (heure d’été d’Europe centrale)
"use strict"

var midiConfig = require("../serveur/midiConfig.json");

var countBusOUT = 0;
for (var i = 0; i < midiConfig.length; i++) {
  if (midiConfig[i].type === "OUT") {
    if (midiConfig[i].spec === "clipToDAW") {
      exports.busMidiDAW = countBusOUT;
    }
    countBusOUT++;
  }
}

// Piece Bitwig en OSC si la paramètre est false
// Sinon Skini parle MIDI
exports.directMidiON = true;

// Pour charger les fonctions et modules de scenes de type GOLEM
exports.scenesON = false;

exports.english = true;

/***********************************
  Paramètres du simulateur
  Si ces valeurs ne sont pas données c'est celle qui
  sont dans le simulateur qui sont utilisées
************************************/
exports.tempoMax = 3010; // En ms
exports.tempoMin = 3000; // En ms
exports.limiteDureeAttente = 20; // En pulsations

/********************************************************
AUTOMATE
*********************************************************/
// Pour un automate conforme à un rechargement selon les déclarations de module HipHop
exports.reactOnPlay = false;

// Pour une réaction à chaque pulsation
exports.pulsationON = false;

/*************************************
CHEMIN DES FICHIERS SONS MP3 pour les clients
Nom du sous répartoire ./sounds/xxxx
*************************************/
exports.soundFilesPath1 = "opus4";

/***************************************
CHEMIN DES PARTITIONS DES PATTERNS ET CONFIG AVEC MUSICIENS
****************************************/
exports.avecMusicien = false; // Pour mettre en place les spécificités au jeu avec des musiciens.
exports.decalageFIFOavecMusicien = 4; // Décalage de la FIFO vide avant le premier pattern dans une FIFO.
exports.patternScorePath1 ="";

/****************************************
ACTIVATION D'ALGORITHME D'ORGANISATION DES FIFOs
Si 0 ou undefined pas d'algorithme.
Si 1 algorithme de réorganisation Début, Milieu, Fin, Neutre (DFMN)
Dans le csv, D -> 1, M -> 2, F->3, N->4 (c'est fixé dans controleAbleton.js)
Si autre ... à créer...
ATTENTION: NE JAMAIS UTILISER EN SITUATION D'INTERACTION SI L'ALGORITHME
PEUT SUPPRIMER DES PATTERNS DES FIFOs
*****************************************/
exports.algoGestionFifo = 0;
exports.shufflePatterns = false;
/*****************************************************************************

Gestion de la Matrice des possibles
Automate de gestion de la matrice des possibles

******************************************************************************/
exports.nbeDeGroupesClients = 2;

function setnbeDeGroupesClients(num) {
  this.nbeDeGroupesClients = num;
}
exports.setnbeDeGroupesClients = setnbeDeGroupesClients;

exports.simulatorInAseperateGroup = false; // Si true, le dernier groupe client est réservé au simulateur.

// Pour un contrôle des Raspberries
exports.useRaspberries = false;
exports.playBufferMessage = "test";
exports.raspOSCPort = 4000;

// La synchro Midi, Link. Synchro Bitwig OSC par défaut si Midi et Link false.
exports.synchoOnMidiClock = false;
exports.synchroLink = true;
exports.synchroSkini = false;
exports.timer = 500;
exports.gameOSCSignals = false;

exports.sensorOSC = false;
exports.tempoSensorsInit = [0,0,0,0,0,0,0,0,,,,];
exports.sensorsSensibilities = [5,5,5,5,5,5,5,5,,,,];

const groupesDesSons = [
  [ "T18",0, "tank",401,200,0,"#5F6262",[],1 ],
  [ "T40",1, "tank",,,0,"#5F6262",[], ],
  [ "T56",2, "tank",,,0,"#5F6262",[], ],
  [ "T72",3, "tank",,,0,"#5F6262",[], ],
  [ "T75",4, "tank",,,0,"#4CAF50",[], ],
  [ "T83",5, "tank",,,0,"#5F6262",[], ],
  [ "T3",6, "tank",400,51,1,"#5F6262",[],1 ],
  [ "T39",7, "tank",,,1,"#5F6262",[], ],
  [ "T45",8, "tank",,,1,"#BCA104",[], ],
  [ "T6",9, "tank",,,1,"#5F6262",[], ],
  [ "T73",10, "tank",,,1,"#5F6262",[], ],
  [ "T82",11, "tank",,,1,"#797bbf",[], ],
  [ "T24",12, "tank",400,51,10,"#5F6262",[],1 ],
  [ "T32",13, "tank",,,10,"#5F6262",[], ],
  [ "T46",14, "tank",,,10,"#5F6262",[], ],
  [ "T49",15, "tank",,,10,"#5F6262",[], ],
  [ "T64",16, "tank",,,10,"#5F6262",[], ],
  [ "T93",17, "tank",,,10,"#5F6262",[], ],
  [ "T48",18, "tank",700,51,11,"#5F6262",[],1 ],
  [ "T77",19, "tank",,,11,"#5F6262",[], ],
  [ "T79",20, "tank",,,11,"#5F6262",[], ],
  [ "T84",21, "tank",,,11,"#5F6262",[], ],
  [ "T86",22, "tank",,,11,"#5F6262",[], ],
  [ "T96",23, "tank",,,11,"#5F6262",[], ],
  [ "T12",24, "tank",700,51,12,"#5F6262",[],1 ],
  [ "T30",25, "tank",,,12,"#5F6262",[], ],
  [ "T51",26, "tank",,,12,"#5F6262",[], ],
  [ "T57",27, "tank",,,12,"#5F6262",[], ],
  [ "T69",28, "tank",,,12,"#5F6262",[], ],
  [ "T8",29, "tank",,,12,"#5F6262",[], ],
  [ "T23",30, "tank",700,51,13,"#5F6262",[],1 ],
  [ "T35",31, "tank",,,13,"#5F6262",[], ],
  [ "T58",32, "tank",,,13,"#5F6262",[], ],
  [ "T60",33, "tank",,,13,"#5F6262",[], ],
  [ "T87",34, "tank",,,13,"#5F6262",[], ],
  [ "T95",35, "tank",,,13,"#5F6262",[], ],
  [ "T19",36, "tank",700,51,14,"#039879",[],1 ],
  [ "T33",37, "tank",,,14,"#5F6262",[], ],
  [ "T47",38, "tank",,,14,"#039879",[], ],
  [ "T50",39, "tank",,,14,"#5F6262",[], ],
  [ "T78",40, "tank",,,14,"#5F6262",[], ],
  [ "T90",41, "tank",,,14,"#5F6262",[], ],
  [ "T10",42, "tank",700,51,15,"#5F6262",[],1 ],
  [ "T21",43, "tank",,,15,"#039879",[], ],
  [ "T31",44, "tank",,,15,"#5F6262",[], ],
  [ "T66",45, "tank",,,15,"#5F6262",[], ],
  [ "T88",46, "tank",,,15,"#5F6262",[], ],
  [ "T91",47, "tank",,,15,"#5F6262",[], ],
  [ "T16",48, "tank",700,51,2,"#039879",[],1 ],
  [ "T28",49, "tank",,,2,"#039879",[], ],
  [ "T42",50, "tank",,,2,"#039879",[], ],
  [ "T54",51, "tank",,,2,"#039879",[], ],
  [ "T59",52, "tank",,,2,"#039879",[], ],
  [ "T62",53, "tank",,,2,"#039879",[], ],
  [ "T1",54, "tank",800,600,3,"#039879",[],1 ],
  [ "T25",55, "tank",,,3,"#039879",[], ],
  [ "T38",56, "tank",,,3,"#039879",[], ],
  [ "T53",57, "tank",,,3,"#039879",[], ],
  [ "T68",58, "tank",,,3,"#039879",[], ],
  [ "T74",59, "tank",,,3,"#039879",[], ],
  [ "T14",60, "tank",800,600,4,"#039879",[],1 ],
  [ "T29",61, "tank",,,4,"#039879",[], ],
  [ "T37",62, "tank",,,4,"#039879",[], ],
  [ "T4",63, "tank",,,4,"#039879",[], ],
  [ "T65",64, "tank",,,4,"#039879",[], ],
  [ "T81",65, "tank",,,4,"#039879",[], ],
  [ "T17",66, "tank",800,600,5,"#039879",[],1 ],
  [ "T27",67, "tank",,,5,"#039879",[], ],
  [ "T41",68, "tank",,,5,"#039879",[], ],
  [ "T43",69, "tank",,,5,"#039879",[], ],
  [ "T55",70, "tank",,,5,"#039879",[], ],
  [ "T7",71, "tank",,,5,"#039879",[], ],
  [ "T15",72, "tank",800,600,6,"#039879",[],1 ],
  [ "T2",73, "tank",,,6,"#039879",[], ],
  [ "T26",74, "tank",,,6,"#039879",[], ],
  [ "T44",75, "tank",,,6,"#039879",[], ],
  [ "T52",76, "tank",,,6,"#039879",[], ],
  [ "T89",77, "tank",,,6,"#039879",[], ],
  [ "T13",78, "tank",400,400,7,"#039879",[],1 ],
  [ "T61",79, "tank",,,7,"#039879",[], ],
  [ "T70",80, "tank",,,7,"#039879",[], ],
  [ "T71",81, "tank",,,7,"#039879",[], ],
  [ "T80",82, "tank",,,7,"#039879",[], ],
  [ "T94",83, "tank",,,7,"#039879",[], ],
  [ "T11",84, "tank",100,350,8,"#039879",[], ],
  [ "T22",85, "tank",,,8,"#039879",[], ],
  [ "T36",86, "tank",,,8,"#039879",[], ],
  [ "T63",87, "tank",,,8,"#039879",[], ],
  [ "T76",88, "tank",,,8,"#039879",[], ],
  [ "T9",89, "tank",,,8,"#039879",[], ],
  [ "T20",90, "tank",100,350,9,"#008CBA",[],1 ],
  [ "T34",91, "tank",,,9,"#039879",[], ],
  [ "T5",92, "tank",,,9,"#008CBA",[], ],
  [ "T67",93, "tank",,,9,"#039879",[], ],
  [ "T85",94, "tank",,,9,"#039879",[], ],
  [ "T92",95, "tank",,,9,"#039879",[], ],
  ];
exports.groupesDesSons = groupesDesSons;
